# model_path: locuslab/phi_grad_ascent_1e-05_forget01
# model_family: phi 


model_family: llama2-7b

use_ori_pretrained: False

use_fine_tune: True

# model_path: locuslab/tofu_ft_llama2-7b
# model_path: locuslab/tofu_ft_llama2-7b/grad_ascent_1e-05_forget10_5/checkpoint-100
# model_path: locuslab/tofu_ft_llama2-7b/grad_diff_1e-05_forget10_5/checkpoint-100
# model_path: locuslab/tofu_ft_llama2-7b/grad_ascent_1e-05_forget10_5/checkpoint-31
# model_path: /home/jovyan/geng/tofu/path/grad_ascent_1e-05_forget10_5/checkpoint-31
# model_path: locuslab/tofu_ft_llama2-7b/grad_ascent_1e-05_forget10_5/checkpoint-12
# model_path: locuslab/tofu_ft_llama2-7b/grad_diff_1e-05_forget10_5/checkpoint-12
# model_path: locuslab/tofu_ft_llama2-7b/idk_1e-05_forget10_5/checkpoint-12
model_path: ./locuslab/tofu_ft_llama2-7b/KL_1e-05_forget10_5/checkpoint-18


save_dir: ./results/${model_path}/attack_activation_steering/ds_size${ds_size}
vectors_path: generate_modified_original_question_activations
multiplier: 0.0

data_path: locuslab/TOFU
split: forget10_perturbed

split_list: ${split}  # retain_perturbed 

question_key: question
answer_key: answer
layers: [5]

base_answer_key: paraphrased_answer
perturbed_answer_key: perturbed_answer

eval_task: eval_log_forget  # eval_log  


generation:
  max_length: 200
  max_new_tokens: null

save_generated_text: true

ds_size: 400   # 300
overwrite: true
batch_size: 1  # 30
reinitialize_weights: false
retain_result: null
forget_loss: KL



# data_path: [locuslab/TOFU]
# split: full
# split_list:
#   - ${split}

# question_key: [question]
# answer_key: [answer]
# eval_task: [eval_log]