retain_result: results/locuslab/tofu_ft_llama2-7b/eval_results/ds_size4000/eval_log_aggregated.json
ckpt_result: results/locuslab/tofu_ft_llama2-7b/eval_results/ds_size4000/eval_log_aggregated.json
method_name: temp
submitted_by: john
save_file:  results/locuslab/tofu_ft_llama2-7b/eval_results/ds_size4000/aggr_result.csv