retain_result: locuslab/phi_grad_ascent_1e-05_forget01/eval_results/ds_size300/eval_log_aggregated.json
ckpt_result: locuslab/phi_grad_ascent_1e-05_forget01/eval_results/ds_size300/eval_log_aggregated.json
method_name: temp
submitted_by: john
save_file: aggr_result.csv